# Generated by Django 3.2.20 on 2023-08-23 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StarsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('stars', models.IntegerField(default=0)),
                ('goals_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal_achiver_api.goalsgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LimitCounterGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('counter', models.IntegerField(default=0)),
                ('limit', models.IntegerField(default=0)),
                ('goals_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal_achiver_api.goalsgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CounterGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('counter', models.IntegerField(default=0)),
                ('goals_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal_achiver_api.goalsgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
